In [97]:
import numpy as np
import copy
import random

## Queation a

### Compute the stationary distribution 

In [98]:
# Initialization
test_number=91
T = 1000
#initial Pi
pi0=[]
pi0.append(1)
for i in range(test_number):
    pi0.append(0)
pi1=[]
for i in range(test_number+1):
    pi1.append(0)

#initial P
P=np.zeros((test_number+1,test_number+1))
# P[0,]=-1
# for i in range(test_number+1):
#     P[i,0]=-1
    
P[0,0]=0.1
P[0,1]=0.9
for i in range(1,test_number):
    P[i,i+1]=0.9-0.01*i
    P[i,0]=0.1+0.01*i

print("transition P:\n",P,type(P),len(P[1,]))
print(P[1,2])
print("pi0:",pi0,type(pi0),len(pi0))
print("pi1:",pi1,type(pi1))

transition P:
 [[0.1  0.9  0.   ... 0.   0.   0.  ]
 [0.11 0.   0.89 ... 0.   0.   0.  ]
 [0.12 0.   0.   ... 0.   0.   0.  ]
 ...
 [0.99 0.   0.   ... 0.   0.01 0.  ]
 [1.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.  ]] <class 'numpy.ndarray'> 92
0.89
pi0: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] <class 'list'> 92
pi1: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] <class 'list'>


In [99]:
# Initialization
test_number=91
T = 1000
#initial Pi
pi0=[]
pi0.append(1)
for i in range(test_number):
    pi0.append(0)
pi1=[]
for i in range(test_number+1):
    pi1.append(0)

#initial P
P=np.zeros((test_number+1,test_number+1))
P[0,0]=0.1
P[0,1]=0.9
for i in range(1,test_number):
    P[i,i+1]=0.9-0.01*i
    P[i,0]=0.1+0.01*i

for t in range(T):
    for i in range(len(pi0)):
        sum = 0
        for j in range(len(P[0,])):
            sum = sum + P[j,i]*pi0[j] 
        pi1[i] = sum
#         pi1[i] = P[0+3*i]*pi0[1-1] + P[1+3*i]*pi0[2-1] +P[2+3*i]*pi0[3-1]
#     pi1=((1/2)*pi0[3-1] , pi0[1-1]+(1/2)*pi0[3-1] , pi0[2-1])
    pi0 = copy.deepcopy(pi1)
print("stationary distribution:")
print(pi1)
print("----")

stationary distribution:
[0.14609754173594203, 0.1314877875623478, 0.11702413093048955, 0.10298123521883078, 0.08959367464038277, 0.07705056019072919, 0.06549297616211981, 0.05501409997618065, 0.045661702980229944, 0.037442596443788556, 0.030328503119468723, 0.02426280249557498, 0.019167613971504235, 0.014950738897773303, 0.01151206895128544, 0.008749172402976934, 0.0065618793022327, 0.004855790683652198, 0.0035447271990661023, 0.0025522035833275935, 0.0018120645441625912, 0.0012684451809138139, 0.0008752271748305317, 0.0005951544788847616, 0.0003987535008527903, 0.00026317731056284163, 0.00017106525186584706, 0.00010948176119414212, 6.897350955230953e-05, 4.276357592243191e-05, 2.6085781312683468e-05, 1.5651468787610076e-05, 9.234366584689941e-06, 5.3559326191201665e-06, 3.0528815928984954e-06, 1.7096136920231577e-06, 9.402875306127369e-07, 5.07755266530878e-07, 2.6911029126136536e-07, 1.3993735145591e-07, 7.13680492425141e-08, 3.568402462125705e-08, 1.7485172064415952e-08, 8.39288259

In [100]:
# Test correct
sum = 0
for i in range(len(pi1)):
    sum = sum+pi1[i]
print(sum)

1.0000000000000735


### use this to find the long-run average replacement costs

In [101]:
#  long-term average reward φ*  
#  φ* = max ∑x,a π*(x,a)r(x,a) excepted
reward = []
Fi = 0
for i in range(len(pi1)):
    reward.append(0.1+0.01*i)
# print(reward)
for i in range(len(pi1)):
    Fi = Fi+pi1[i]*reward[i]
Fi

0.14609754173594203

## Question b

### Simulate the system for a long period and verify that you get (approximately) the same answer

In [ ]:
state = 0
cost = 0
for t in range(10):
    

## Question c

### Solve the average-cost Poisson equation

In [102]:
# Possion EQ 
# V* + φ*e = r + PV*
# print(reward)
state = 91
A = np.zeros((state,state+1))
for i in range(state): # 3 rows, s states in total 
    A[i,i] = 1 # the row state be 1 in initial
    A[i,state] = 1 # φ=1
    for j in range(state):
        A[i,j] = A[i,j] - P[i,j]
#         print(i,j,P[i,j],A[i,j])
A

array([[ 0.9 , -0.9 ,  0.  , ...,  0.  ,  0.  ,  1.  ],
       [-0.11,  1.  , -0.89, ...,  0.  ,  0.  ,  1.  ],
       [-0.12,  0.  ,  1.  , ...,  0.  ,  0.  ,  1.  ],
       ...,
       [-0.98,  0.  ,  0.  , ..., -0.02,  0.  ,  1.  ],
       [-0.99,  0.  ,  0.  , ...,  1.  , -0.01,  1.  ],
       [-1.  ,  0.  ,  0.  , ...,  0.  ,  1.  ,  1.  ]])

In [140]:
for i in range(state):# make V(0) = 0
    A[i,0]=0
# print(type(A))
# print(A)
equation = []
for i in range(state):
    row = []
    for j in range(1,state+1):
        row.append(A[i,j])
    equation.append(row)
# print(type(equation))
# print(len(equation))
# print(len(equation[0]))

In [104]:
value = np.linalg.solve(equation,reward[0:state])
print(value)
# V(0)=0, the last value 0.14609754 is φ

[0.05121949 0.09810903 0.14114383 0.1807372  0.2172497  0.25099676
 0.28225512 0.31126827 0.33825099 0.36339325 0.38686349 0.40881143
 0.42937048 0.44865976 0.46678593 0.48384463 0.49992185 0.51509506
 0.52943416 0.5430024  0.55585706 0.56805015 0.57962896 0.59063657
 0.60111229 0.61109205 0.62060874 0.6296925  0.63837104 0.64666981
 0.65461225 0.66221999 0.66951298 0.67650969 0.6832272  0.68968134
 0.69588683 0.7018573  0.70760546 0.71314314 0.71848136 0.72363041
 0.72859991 0.73339883 0.73803559 0.74251806 0.74685364 0.75104926
 0.75511144 0.7590463  0.7628596  0.76655677 0.77014293 0.77362291
 0.77700125 0.78028226 0.78347001 0.78656835 0.78958092 0.79251117
 0.79536237 0.79813762 0.80083988 0.80347193 0.80603644 0.80853593
 0.81097281 0.81334937 0.81566779 0.81793014 0.82013841 0.82229449
 0.82440018 0.82645721 0.82846723 0.8304318  0.83235243 0.83423057
 0.83606759 0.83786481 0.8396235  0.84134486 0.84303008 0.84468024
 0.84629644 0.8478797  0.849431   0.85095129 0.85244148 0.8539

In [105]:
def solve_Possion_phi(alpha,p1,p2,reward1,reward2):
    # V* + φ*e = r + PV*
    reward = []
    state = len(alpha)
    Equation = np.zeros((state,state+1))
    for i in range(state): # 3 rows, s states in total 
        Equation[i,i] = 1 # the row state be 1 in initial
        Equation[i,state] = 1 # φ=1
        if(alpha[i]==1):
            for j in range(state):
                Equation[i,j] = Equation[i,j] - p1[i,j]
            reward.append(reward1[i])
            # print(i,j,P[i,j],A[i,j])
        if(alpha[i]==2):
            for j in range(state):
                Equation[i,j] = Equation[i,j] - p2[i,j]
            reward.append(reward2[i])
            # print(i,j,P[i,j],A[i,j])           
    for i in range(state):# make V(0) = 0
        Equation[i,0]=0
#     print("\nEquation: \n",Equation)
    equation = []
    for i in range(state):
        row = []
        for j in range(1,state+1):
            row.append(Equation[i,j])
        equation.append(row)
#     print("equation:",equation)
#     print("\nreward:\n",reward)
    value = np.linalg.solve(equation,reward)
#     print("\nvalue:\n",value)
#     print("\nPhi:",value[90])
    return(value[90])

In [106]:
def solve_Possion_V(alpha,p1,p2,reward1,reward2):
#     print(alpha)
#     print(P1)
#     print(P2)
    # V* + φ*e = r + PV*
    reward = []
    state = len(alpha)
    Equation = np.zeros((state,state+1))
    for i in range(state): # 3 rows, s states in total 
        Equation[i,i] = 1 # the row state be 1 in initial
        Equation[i,state] = 1 # φ=1
        if(alpha[i]==1):
            for j in range(state):
                Equation[i,j] = Equation[i,j] - p1[i,j]
            reward.append(reward1[i])
            # print(i,j,P[i,j],A[i,j])
        if(alpha[i]==2):
            for j in range(state):
                Equation[i,j] = Equation[i,j] - p2[i,j]
            reward.append(reward2[i])
            # print(i,j,P[i,j],A[i,j])           
    for i in range(state):# make V(0) = 0
        Equation[i,0]=0
#     print("\nEquation: \n",Equation)
    equation = []
    for i in range(state):
        row = []
        for j in range(1,state+1):
            row.append(Equation[i,j])
        equation.append(row)
#     print("equation:",equation)
#     print("\nreward:\n",reward)
    value = np.linalg.solve(equation,reward)
#     print("\nvalue:\n",value)
#     print("\nPhi:",value[90])
    V = [0]
    for i in range(90):
        V.append(value[i])
    return(V)


## Question d
#### Preventive replacement is possible at cost 0.5. What is the average optimal policy?
• policy iteration
• value iteration

In [107]:
#initial P1, P2, reward1, reward2
# action 1: p = linear growth, success + fail = 1, reward = p*fail
P1 = np.zeros((91,91+1))  
P1[0,0]=0.1
P1[0,1]=0.9
for i in range(1,91):
    P1[i,i+1]=0.9-0.01*i
    P1[i,0]=0.1+0.01*i
# print("transition P1:\n",P1,type(P1),len(P1[1,]))
reward1 = []
for i in range(91):
    reward1.append(round(P1[i,0],2))
# # action 2: p = 1, reward = 0.5
P2 = np.zeros((91,91+1))
for i in range(91):
    P2[i,0]=1
reward2 = []
for i in range(91):
    reward2.append(0.5)
print(P1)
print(P1[90,0])
print(reward1)
print(P2)
print(P2[90,0])
print(reward2)

[[0.1  0.9  0.   ... 0.   0.   0.  ]
 [0.11 0.   0.89 ... 0.   0.   0.  ]
 [0.12 0.   0.   ... 0.   0.   0.  ]
 ...
 [0.98 0.   0.   ... 0.02 0.   0.  ]
 [0.99 0.   0.   ... 0.   0.01 0.  ]
 [1.   0.   0.   ... 0.   0.   0.  ]]
1.0
[0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6, 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7, 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
1.0
[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 

In [109]:
# Excepted Policy iteration 
phi_list = []
for i in range(91):
    alpha = [1]*91 # at beginning, all action 1
    alpha[i]=2
#     print(i,solve_Possion(alpha,P1,P2,reward1,reward2))
    phi_list.append(solve_Possion_phi(alpha,P1,P2,reward1,reward2))
print(phi_list)    
print("\nmin phi:",min(phi_list),",Preventive replacement at:",np.argmin(phi_list))

# minimize φ, and take Preventive replacement at 13 is optimal policy

[0.5, 0.2894736842105263, 0.22195483154387263, 0.19013001045251154, 0.17251941566593487, 0.16194911880867, 0.15533331349178886, 0.15112035647143765, 0.14844188296714134, 0.1467728129471102, 0.1457770679715917, 0.14523057041948506, 0.1449797973330045, 0.14491799482409007, 0.14497070705380208, 0.1450864652162317, 0.14523046530673414, 0.1453800608861978, 0.14552142201710117, 0.14564699530394223, 0.14575355397133904, 0.14584070878893937, 0.14590979234304416, 0.1459630493287368, 0.14600307530144738, 0.14603245207724302, 0.14605353302183768, 0.14606833715727302, 0.14607851751484513, 0.14608537607457342, 0.14608990438825936, 0.1460928350855136, 0.1460946945843495, 0.1460958513358114, 0.1460965568506044, 0.14609697871672345, 0.14609722600689817, 0.14609736809147233, 0.14609744809767708, 0.14609749223966323, 0.14609751609762295, 0.14609752872628834, 0.1460975352711743, 0.14609753859113958, 0.1460975402389491, 0.1460975410389059, 0.14609754141860976, 0.14609754159475216, 0.1460975416745761, 0.14

In [165]:
# Policy iteration
# V + φ = rα + PαV
# φ = rα + PαV - V
alpha = [1]*91
new_alpha = [0]*91
for t in range(100):
#     print("alpha:",alpha)
    Vt = solve_Possion_V(alpha,P1,P2,reward1,reward2)
#     print(Vt)
    for i in range(91):
        v1 = reward1[i]
        v2 = reward2[i]
        for j in range(91):
            v1 = v1 + P1[i,j]*Vt[j]
            v2 = v2 + P2[i,j]*Vt[j]
        new_alpha[i]=np.argmax([-v1,-v2])+1
    if(alpha==new_alpha):
        print(t,alpha==new_alpha)
        break
    alpha = copy.deepcopy(new_alpha)
print("optimal alpha is:",alpha,len(alpha))

2 True
optimal alpha is: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] 91


In [169]:
# Value iteration
Vt = [0]*91
Vt1 = [0]*91
phi_list = [0]*91
for t in range(10000):
    for i in range(91):
        v1 = reward1[i]
        v2 = reward2[i]
        for j in range(91):
            v1 = v1 + P1[i,j]*Vt[j]
            v2 = v2 + P2[i,j]*Vt[j]
        Vt1[i]=min(v1,v2)
        phi_list[i]=Vt1[i]-Vt[i]
    Vt=copy.deepcopy(Vt1)
    if(max(phi_list)-min(phi_list)<0.001):
#         print("iteration times:",t,"\nmax(V_t+1 - Vt)-min(V_t+1 - Vt):",max(phi_list)-min(phi_list))
        print(phi_list)
        break

[0.14504668763113804, 0.14507172234834975, 0.1450700656678121, 0.14504967858013273, 0.14501685509288365, 0.14497655016050093, 0.1449326422484174, 0.14423550704200228, 0.14435631779337932, 0.1445658524868776, 0.14473607797864974, 0.14478273176831946, 0.14489070983770969, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.14498492329738522, 0.1449849232973

In [138]:
# find the policy
alpha = [0]*91
for i in range(len(Vt1)):
    v1 = reward1[i]
    v2 = reward2[i]
    for j in range(91):
        v1 = v1 + P1[i,j]*Vt[j]
        v2 = v2 + P2[i,j]*Vt[j]
#     print(v1,v2)
    alpha[i]=np.argmax([-v1,-v2])+1
print("alpha:",alpha)

alpha: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [58]:
print(np.argmax([2,1]))

0


In [229]:
V = [0]*91
newV = [0]*91
alpha=[]
for i in range(91):
    v1 = reward1[i]
    v2 = reward2[i]
    for j in range(91):
        v1 = v1 + P1[i,j]*V[j]
        v2 = v2 + P2[i,j]*V[j]
#     print(v1,v2,max(v1,v2))
    V[i] = max(v1,v2)  
print(V)  


[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.51, 0.5249999999999999, 0.54, 0.5549999999999999, 0.5700000000000001, 0.585, 0.6000000000000001, 0.615, 0.6300000000000001, 0.645, 0.6600000000000001, 0.675, 0.69, 0.705, 0.72, 0.735, 0.75, 0.765, 0.78, 0.795, 0.81, 0.8250000000000001, 0.8400000000000001, 0.8550000000000001, 0.8699999999999999, 0.885, 0.8999999999999999, 0.915, 0.9299999999999999, 0.9450000000000001, 0.96, 0.9750000000000001, 0.99, 1.0050000000000001, 1.02, 1.035, 1.0499999999999998, 1.065, 1.08, 1.095, 1.1099999999999999, 1.125, 1.1400000000000001, 1.155, 1.17, 1.185, 1.2000000000000002, 1.2149999999999999, 1.23, 1.2449999999999999, 1.26, 1.275, 1.29, 1.305, 1.32, 1.335, 1.35, 1.365, 1.3800000000000001, 1.395, 1.41, 1.4249999999999998, 1.44, 1.455, 1.47, 1.4849999999999999, 1.5]


### Example

In [163]:
# teacher's example
pi0_tuple = [1,0,0]
pi1_tuple = [0,0,0]
pi0 = list(pi0_tuple)
pi1 = list(pi1_tuple)

P = [0,0,1/2,  1,0,1/2,  0,1,0]
P1 = np.zeros((3+1,3+1))
P1[0,]=-1
T = 10000
for i in range(1,3+1):
    P1[i,0]=-1

    
P1[1,1]=P1[2,1]=P1[2,2]=P1[1,3]=P1[3,3]=0
P1[3,1]=P1[3,2]=1/2
P1[1,2]=P1[2,3]=1
print(type(P1))
print(pi0)

<class 'numpy.ndarray'>
[1, 0, 0]


In [164]:
for t in range(T):
    for i in range(len(pi1)):
        sum = 0
        for j in range(len(pi0)):
            sum = sum+ P1[j+1,i+1]*pi0[j]
        pi1[i] = sum
#         pi1[i] = P[0+3*i]*pi0[1-1] + P[1+3*i]*pi0[2-1] +P[2+3*i]*pi0[3-1]
#     pi1=((1/2)*pi0[3-1] , pi0[1-1]+(1/2)*pi0[3-1] , pi0[2-1])
    pi0 = copy.deepcopy(pi1)
print(pi1)

[0.2, 0.4, 0.4]


In [165]:
state=1
visits=[-1,0,0,0]
for i in range(T):
    visits[state] = visits[state]+1
    if(state==3):
        state = random.randint(1,2)
#         print("state=3")
    else:
        state = state+1
print(visits)

[-1, 2006, 3997, 3997]


### Possion Equation

In [166]:
# Possion Equation
A = [[-1,0,1],[1,-1,1],[-0.5,1,1]]
r = [0,1,2]

solution = np.linalg.solve(A,r)
print(solution)

[1.2 1.4 1.2]


In [167]:
print(type(A))
A

<class 'list'>


[[-1, 0, 1], [1, -1, 1], [-0.5, 1, 1]]

In [168]:
state = 3
A = np.zeros((state,state+1))
for i in range(state): # 3 rows, s states in total 
    A[i,i] = 1 # the row state be 1 in initial
    A[i,state] = 1 # φ=1
    for j in range(state):
        A[i,j] = A[i,j] - P1[i+1,j+1]
#         print(i+1,j+1,P1[i+1,j+1],A[i,j])

for i in range(state):# make V(1) = 0
    A[i,0]=0
# print(type(A))
# print(A)
equation = []
for i in range(state):
    row = []
    for j in range(1,state+1):
        row.append(A[i,j])
    equation.append(row)
print(type(equation))
print(equation)

<class 'list'>
[[-1.0, 0.0, 1.0], [1.0, -1.0, 1.0], [-0.5, 1.0, 1.0]]


In [169]:
solution = np.linalg.solve(equation,r)
print(solution)

[1.2 1.4 1.2]


In [172]:
V=[0]
for i in range(2):
    V.append(solution[i])
print(V)

[0, 1.2, 1.4]


### Backward iteration

In [202]:
V = [0,0,0]
# V = np.mat(V)
r1 = [0,1,2]
r2 = [0,1,3]
# alpha = [1,1]
state_number = len(r1)

# print(type(a))
# print(a)
# P1 = np.matrix([[0.5, 0.5], [0, 1]])
# P2 = np.matrix([[0.5,0.5]]*2)
P1 = np.matrix([[0,1,0],[0,0,1],[0.5,0.5,0]])
P2 = np.matrix([[0,1,0],[0,0,1],[1,0,0]])

print(P1,type(P1))
print(r1)
print()
print(P2,type(P2))
print(r2)
print(V,type(V))

[[0.  1.  0. ]
 [0.  0.  1. ]
 [0.5 0.5 0. ]] <class 'numpy.matrix'>
[0, 1, 2]

[[0 1 0]
 [0 0 1]
 [1 0 0]] <class 'numpy.matrix'>
[0, 1, 3]
[0, 0, 0] <class 'list'>


In [203]:
alpha=[]
for i in range(3):
    v1 = r1[i]
    v2 = r2[i]
    for j in range(3):
        v1 = v1 + P1[i,j]*V[j]
        v2 = v2 + P2[i,j]*V[j]
    print(v1,v2,max(v1,v2))
    V[i] = max(v1,v2)  
print(V)  

for i in range(3):
    v1 = r1[i]
    v2 = r2[i]
    for j in range(3):
        v1 = v1 + P1[i,j]*V[j]
        v2 = v2 + P2[i,j]*V[j]
    a=np.argmax([v1,v2])+1
    print(a)
    alpha.append(a) 
print(alpha)

0.0 0 0.0
1.0 1.0 1.0
2.5 3.0 3.0
[0.0, 1.0, 3.0]
1
1
2
[1, 1, 2]


In [204]:
print(V)
phi = []
for i in range(3):
    if alpha[i]==1:
        phie = r1[i]
        for j in range(3):
            phie = phie + P1[i,j]*V[j] 
        phie = phie -V[j]
        phi.append(phie)
    if alpha[i]==2:
        phie = r2[i]
        for j in range(3):
            phie = phie + P2[i,j]*V[j]
        phie = phie -V[j]
        phi.append(phie)
print(phi)

[0.0, 1.0, 3.0]
[-2.0, 1.0, 0.0]
